### ISSUE TITLE
Fix recurring ContentCafe error

### ISSUE THREAD

**Issue by courte** [NYPL-Simplified/metadata_wrangler#143]
I'm seeing this error repeatedly in the logs for the Content Cafe coverage provider.

```
Traceback (most recent call last):
File "/var/lib/app/metadata/content_cafe.py", line 55, in process_item
  self.content_cafe.mirror_resources(identifier)
File "/var/lib/app/metadata/content_cafe.py", line 134, in mirror_resources
  self.mirror.uploader.mirror_one(representation)
File "/var/lib/app/metadata/core/s3.py", line 203, in mirror_one
  return self.mirror_batch([representation])
File "/var/lib/app/metadata/core/s3.py", line 250, in mirror_batch
  for response in self.pool.as_completed(requests):
File "/var/lib/app/env/local/lib/python2.7/site-packages/tinys3/pool.py", line 71, in as_completed
  yield r.result()
File "/var/lib/app/env/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
  return self.__get_result()
File "/var/lib/app/env/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
  result = self.fn(*self.args, **self.kwargs)
File "/var/lib/app/env/local/lib/python2.7/site-packages/tinys3/request_factory.py", line 178, in run
  auth=self.auth)
File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/api.py", line 122, in put
  return request('put', url, data=data, **kwargs)
File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
  response = session.request(method=method, url=url, **kwargs)
File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/sessions.py", line 444, in request
  data = data or {},
File "/var/lib/app/env/local/lib/python2.7/site-packages/tinys3/util.py", line 75, in __len__
  start_pos = o.tell()
AttributeError: 'NoneType' object has no attribute 'tell'
```

**Comment by courte** [comment]
Attempts to resolve this issue with #148 were ineffective. However, although it's logging every time the coverage provider runs (currently hourly), this error is only impacting 35 identifiers.
