### ISSUE TITLE
Exception extracting subject name from OCLC-LD

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/metadata_wrangler#41]
While looking at the logs of the metadata wrangler's identifier resolution script I noticed an exception in OCLC's metadata extraction code:

```
2016-03-17 17:15:25,985:root:INFO:model.py:Cached http://www.worldcat.org/oclc/57657089.jsonld
2016-03-17 17:15:26,355:OCLC Linked Data Client:INFO:oclc.py:Processing edition None: None
2016-03-17 17:15:26,403:Identifier Resolution Manager:ERROR:monitor.py:FAILURE on Gutenberg ID/9536 ID=2421639 wr=267543 ("The Newcomes"): Traceback (most recent call last):
  File "/home/ec2-user/metadata/core/monitor.py", line 147, in resolve_and_handle_result
    self.resolve(unresolved_identifier)
  File "/home/ec2-user/metadata/core/monitor.py", line 183, in resolve
    self.finalize(unresolved_identifier)
  File "/home/ec2-user/metadata/monitor.py", line 153, in finalize
    self.resolve_equivalent_oclc_identifiers(identifier)
  File "/home/ec2-user/metadata/monitor.py", line 195, in resolve_equivalent_oclc_identifiers
    self.oclc_linked_data.ensure_coverage(oclc_id)
  File "/home/ec2-user/metadata/core/coverage.py", line 179, in ensure_coverage
    result = self.process_item(identifier)
  File "/home/ec2-user/metadata/oclc.py", line 1283, in process_item
    for metadata in self.api.info_for(identifier):
  File "/home/ec2-user/metadata/oclc.py", line 505, in info_for
    info = self.book_info_to_metadata(subgraph, book)
  File "/home/ec2-user/metadata/oclc.py", line 531, in book_info_to_metadata
    example_uris) = self.extract_useful_data(subgraph, book_info)
  File "/home/ec2-user/metadata/oclc.py", line 457, in extract_useful_data
    [subject_name] = name_value
ValueError: too many values to unpack
```
It doesn't happen every single time but it does happen pretty often. I don't see anything unusual in the OCLC-LD file that supposedly caused the problem, but I haven't looked into it too deeply.

**Comment by courte** [comment]
Fun! I'll look into this.

**Comment by courte** [comment]
There's also a recurring issues with `subject_data` not existing:

```
2016-03-18 17:59:57,996:root:INFO:model.py:Cached http://www.worldcat.org/oclc/799681494.jsonld
2016-03-18 17:59:58,263:OCLC Linked Data Client:INFO:oclc.py:Processing edition None: None
2016-03-18 17:59:58,264:Identifier Resolution Manager:ERROR:monitor.py:FAILURE on Gutenberg ID/8756 ID=2439524 wr=267575 ("The Monster Men"): Traceback (most recent call last):
  File "/home/ec2-user/metadata/core/monitor.py", line 147, in resolve_and_handle_result
    self.resolve(unresolved_identifier)
  File "/home/ec2-user/metadata/core/monitor.py", line 183, in resolve
    self.finalize(unresolved_identifier)
  File "/home/ec2-user/metadata/monitor.py", line 153, in finalize
    self.resolve_equivalent_oclc_identifiers(identifier)
  File "/home/ec2-user/metadata/monitor.py", line 195, in resolve_equivalent_oclc_identifiers
    self.oclc_linked_data.ensure_coverage(oclc_id)
  File "/home/ec2-user/metadata/core/coverage.py", line 179, in ensure_coverage
    result = self.process_item(identifier)
  File "/home/ec2-user/metadata/oclc.py", line 1283, in process_item
    for metadata in self.api.info_for(identifier):
  File "/home/ec2-user/metadata/oclc.py", line 505, in info_for
    info = self.book_info_to_metadata(subgraph, book)
  File "/home/ec2-user/metadata/oclc.py", line 531, in book_info_to_metadata
    example_uris) = self.extract_useful_data(subgraph, book_info)
  File "/home/ec2-user/metadata/oclc.py", line 412, in extract_useful_data
    [subject_data] = cls.internal_lookup(subgraph, [uri])
ValueError: need more than 0 values to unpack
```
