### ISSUE TITLE
500 error fulfillng loan

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/metadata_wrangler#70]
```

Traceback (most recent call last):
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/newrelic-2.52.0.40/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "./api/routes.py", line 95, in decorated
    return f(*args, **kwargs)
  File "./core/app_server.py", line 165, in decorated
    v = f(*args, **kwargs)
  File "./api/routes.py", line 160, in fulfill
    return app.manager.loans.fulfill(data_source, identifier_type, identifier, mechanism_id)
  File "./api/controller.py", line 680, in fulfill
    fulfillment = self.circulation.fulfill(patron, pin, pool, mechanism)
  File "./api/circulation.py", line 371, in fulfill
    __transaction.commit()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 710, in _emit_update_statements
    (table.description, len(records), rows))
StaleDataError: UPDATE statement on table 'loans' expected to update 1 row(s); 0 were matched.
filename: app_server.py
host: ip-10-225-3-168
message: Exception in web app: UPDATE statement on table 'loans' expected to update 1 row(s); 0 were matched. 
```

**Comment by aslagle** [comment]
This is in the wrong repo, but it's been fixed. https://github.com/NYPL-Simplified/circulation/pull/269
